### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by miguelshta21** [marcel-valdez/tibia_terminator#2]
`python tibia_terminator.py
Traceback (most recent call last):
  File "/home/aeris/Escritorio/tibia_terminator-master/tibia_terminator.py", line 14, in <module>
    from char_keeper import CharKeeper
  File "/home/aeris/Escritorio/tibia_terminator-master/char_keeper.py", line 5, in <module>
    from equipment_keeper import EquipmentKeeper
  File "/home/aeris/Escritorio/tibia_terminator-master/equipment_keeper.py", line 5, in <module>
    from equipment_reader import (RingName, AmuletName)
  File "/home/aeris/Escritorio/tibia_terminator-master/equipment_reader.py", line 112, in <module>
    class EquipmentReader(ScreenReader):
  File "/home/aeris/Escritorio/tibia_terminator-master/equipment_reader.py", line 125, in EquipmentReader
    def get_equipment_status(self) -> FutureValue[EquipmentStatus]:
NameError: name 'EquipmentStatus' is not defined
`

**Comment by marcel-valdez** [comment]
I talked with @miguelshta21 over discord and explained how to use it. Overall... it is hard to use and multiple usability improvement issues were registered as a result.

**Comment by miguelshta21** [comment]
hola marcel estas?
